# stock: RabbitMQDefault.py
chainlink:
  chainlinkname: default
  next link: "127.0.0.1"
  remoteconf: false
  type: rabbitmq
  rabbitmq:
    hostname: "{{ gethostname() }}"
    erlangcookie: '{{ getCookieInfo() }}'
    profile:
      # stock profiles are provided by chainchomp
      stock: true
      type: 'default'
  kafka:
    #TODO setup for kafka
    hostname: "{{ gethostname() }}"
    erlangcookie: '{{ getCookieInfo() }}'
    profile:
      # stock profiles are provided by chainchomp
      stock: true
      type: 'default'